#!/bin/bash
# Fledgely One-Click Deployment Script
# Apache 2.0 License
#
# Usage: ./scripts/deploy.sh [project_id] [region]
#
# This script performs a complete Fledgely deployment to GCP.
# Deployment should complete in <15 minutes (NFR51).

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored message
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Print banner
print_banner() {
    echo ""
    echo "============================================"
    echo "    Fledgely One-Click GCP Deployment"
    echo "============================================"
    echo ""
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check terraform
    if ! command -v terraform &> /dev/null; then
        log_error "Terraform is not installed. Please install Terraform 1.5.0 or later."
        exit 1
    fi

    TERRAFORM_VERSION=$(terraform version -json | grep -o '"terraform_version":"[^"]*' | cut -d'"' -f4)
    log_info "Terraform version: $TERRAFORM_VERSION"

    # Check gcloud
    if ! command -v gcloud &> /dev/null; then
        log_error "gcloud CLI is not installed. Please install Google Cloud SDK."
        exit 1
    fi

    # Check gcloud authentication
    if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1 > /dev/null 2>&1; then
        log_error "Not authenticated with gcloud. Run: gcloud auth login"
        exit 1
    fi

    log_success "Prerequisites check passed"
}

# Get or prompt for project ID
get_project_id() {
    if [ -n "${1:-}" ]; then
        PROJECT_ID="$1"
    elif [ -f "terraform.tfvars" ]; then
        PROJECT_ID=$(grep 'project_id' terraform.tfvars | cut -d'=' -f2 | tr -d ' "' || true)
    fi

    if [ -z "${PROJECT_ID:-}" ]; then
        read -p "Enter GCP Project ID: " PROJECT_ID
    fi

    echo "$PROJECT_ID"
}

# Get or prompt for region
get_region() {
    if [ -n "${1:-}" ]; then
        REGION="$1"
    elif [ -f "terraform.tfvars" ]; then
        REGION=$(grep 'region' terraform.tfvars | cut -d'=' -f2 | tr -d ' "' || true)
    fi

    if [ -z "${REGION:-}" ]; then
        REGION="us-central1"
    fi

    echo "$REGION"
}

# Create terraform.tfvars if it doesn't exist
create_tfvars() {
    local project_id="$1"
    local region="$2"

    if [ ! -f "terraform.tfvars" ]; then
        log_info "Creating terraform.tfvars..."
        cat > terraform.tfvars << EOF
# Fledgely Terraform Configuration
# Generated by deploy.sh on $(date)

project_id = "$project_id"
region     = "$region"
EOF
        log_success "Created terraform.tfvars"
    else
        log_info "Using existing terraform.tfvars"
    fi
}

# Initialize Terraform
init_terraform() {
    log_info "Initializing Terraform..."
    terraform init -upgrade
    log_success "Terraform initialized"
}

# Plan deployment
plan_deployment() {
    log_info "Planning deployment..."
    terraform plan -out=tfplan
    log_success "Plan created"
}

# Apply deployment
apply_deployment() {
    log_info "Applying deployment..."
    local start_time=$(date +%s)

    terraform apply tfplan

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    local minutes=$((duration / 60))
    local seconds=$((duration % 60))

    log_success "Deployment completed in ${minutes}m ${seconds}s"

    # Check against NFR51 (15 minutes)
    if [ $duration -gt 900 ]; then
        log_warn "Deployment took longer than 15 minutes (NFR51)"
    else
        log_success "Deployment time within NFR51 requirement (<15 minutes)"
    fi

    # Clean up plan file
    rm -f tfplan
}

# Show outputs
show_outputs() {
    log_info "Deployment outputs:"
    echo ""
    terraform output deployment_summary
    echo ""
    log_info "Next steps:"
    terraform output next_steps
}

# Main function
main() {
    print_banner

    # Record start time
    DEPLOY_START=$(date +%s)

    # Check we're in the terraform directory
    if [ ! -f "main.tf" ]; then
        log_error "Please run this script from the terraform directory"
        exit 1
    fi

    check_prerequisites

    # Get configuration
    PROJECT_ID=$(get_project_id "${1:-}")
    REGION=$(get_region "${2:-}")

    log_info "Project ID: $PROJECT_ID"
    log_info "Region: $REGION"

    # Confirm deployment
    echo ""
    read -p "Deploy Fledgely to $PROJECT_ID in $REGION? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_warn "Deployment cancelled"
        exit 0
    fi

    create_tfvars "$PROJECT_ID" "$REGION"
    init_terraform
    plan_deployment

    echo ""
    read -p "Apply this plan? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_warn "Deployment cancelled"
        rm -f tfplan
        exit 0
    fi

    apply_deployment
    show_outputs

    # Calculate total time
    DEPLOY_END=$(date +%s)
    TOTAL_DURATION=$((DEPLOY_END - DEPLOY_START))
    TOTAL_MINUTES=$((TOTAL_DURATION / 60))
    TOTAL_SECONDS=$((TOTAL_DURATION % 60))

    echo ""
    log_success "============================================"
    log_success "Fledgely deployment complete!"
    log_success "Total time: ${TOTAL_MINUTES}m ${TOTAL_SECONDS}s"
    log_success "============================================"
    echo ""
    log_info "Run ./scripts/verify.sh to verify the deployment"
}

main "$@"
