/**
 * AgreementReviewRequest Contract - Story 34.5.3 Task 1
 *
 * Zod schemas for agreement review requests.
 * AC4: Rate Limiting (60-Day Cooldown)
 * AC6: Review Request Tracking
 *
 * CRITICAL: All messaging must be invitation-based, not demand-based.
 */

import { z } from 'zod'

// ============================================
// Constants
// ============================================

/**
 * Number of days a child must wait between review requests.
 * AC4: Rate limiting prevents request spam while allowing genuine requests.
 */
export const REVIEW_REQUEST_COOLDOWN_DAYS = 60

/**
 * Number of days before a review request expires if not addressed.
 */
export const REVIEW_REQUEST_EXPIRY_DAYS = 30

// ============================================
// Status Schema
// ============================================

/**
 * Review request status enum.
 * - pending: Request submitted, awaiting parent acknowledgment
 * - acknowledged: Parent has seen the request
 * - reviewed: Family has discussed/reviewed the agreement
 * - expired: Request expired without being addressed
 */
export const reviewRequestStatusSchema = z.enum(['pending', 'acknowledged', 'reviewed', 'expired'])

export type ReviewRequestStatus = z.infer<typeof reviewRequestStatusSchema>

// ============================================
// Agreement Review Request Schema
// ============================================

/**
 * Full agreement review request schema.
 * AC6: Tracks request date, child ID, family ID for metrics.
 */
export const agreementReviewRequestSchema = z.object({
  /** Unique identifier for this review request */
  id: z.string(),
  /** Family this request belongs to */
  familyId: z.string(),
  /** Child who initiated the request */
  childId: z.string(),
  /** Child's display name for notifications */
  childName: z.string(),
  /** Agreement being requested for review */
  agreementId: z.string(),
  /** When the request was submitted */
  requestedAt: z.date(),
  /** Current status of the request */
  status: reviewRequestStatusSchema,
  /** When parent acknowledged the request (null if not yet) */
  acknowledgedAt: z.date().nullable(),
  /** When the review was completed (null if not yet) */
  reviewedAt: z.date().nullable(),
  /** Suggested discussion areas based on history */
  suggestedAreas: z.array(z.string()),
  /** Whether parent notification has been sent */
  parentNotificationSent: z.boolean(),
  /** When the request expires (30 days after submission) */
  expiresAt: z.date(),
})

export type AgreementReviewRequest = z.infer<typeof agreementReviewRequestSchema>

// ============================================
// Cooldown Status Schema
// ============================================

/**
 * Cooldown status for checking if a child can request a review.
 * AC4: 60-day cooldown between requests.
 */
export const cooldownStatusSchema = z.object({
  /** Whether the child can currently make a request */
  canRequest: z.boolean(),
  /** When the last request was made (null if never) */
  lastRequestAt: z.date().nullable(),
  /** When the next request will be available (null if already available) */
  nextAvailableAt: z.date().nullable(),
  /** Number of days remaining in cooldown (0 if can request) */
  daysRemaining: z.number().int().min(0),
})

export type CooldownStatus = z.infer<typeof cooldownStatusSchema>

// ============================================
// Create Request Schema
// ============================================

/**
 * Schema for creating a new review request.
 * Minimal input - other fields are generated by the service.
 */
export const createAgreementReviewRequestSchema = z.object({
  familyId: z.string().min(1),
  childId: z.string().min(1),
  childName: z.string().min(1),
  agreementId: z.string().min(1),
})

export type CreateAgreementReviewRequest = z.infer<typeof createAgreementReviewRequestSchema>

// ============================================
// Utility Functions
// ============================================

/**
 * Calculate cooldown status based on last request date.
 * AC4: 60-day cooldown between requests.
 *
 * @param lastRequestAt - Date of the last review request, or null if none
 * @returns Cooldown status indicating if a new request can be made
 */
export function calculateCooldownStatus(lastRequestAt: Date | null): CooldownStatus {
  if (lastRequestAt === null) {
    return {
      canRequest: true,
      lastRequestAt: null,
      nextAvailableAt: null,
      daysRemaining: 0,
    }
  }

  const now = new Date()
  const cooldownEnd = new Date(lastRequestAt)
  cooldownEnd.setDate(cooldownEnd.getDate() + REVIEW_REQUEST_COOLDOWN_DAYS)

  const msRemaining = cooldownEnd.getTime() - now.getTime()
  const daysRemaining = Math.max(0, Math.ceil(msRemaining / (1000 * 60 * 60 * 24)))

  const canRequest = msRemaining <= 0

  return {
    canRequest,
    lastRequestAt,
    nextAvailableAt: canRequest ? null : cooldownEnd,
    daysRemaining,
  }
}
