# Fledgely Terraform Module - Backup
# Apache 2.0 License

# =============================================================================
# Backup Storage Bucket
# =============================================================================

resource "google_storage_bucket" "backups" {
  project  = var.project_id
  name     = "${var.project_id}-fledgely-backups"
  location = var.location

  # Prevent accidental deletion
  force_destroy = false

  # Use standard storage for recent backups
  storage_class = "STANDARD"

  # Uniform bucket-level access for security
  uniform_bucket_level_access = true

  # Prevent public access
  public_access_prevention = "enforced"

  # Versioning for additional protection
  versioning {
    enabled = true
  }

  # Lifecycle rules for retention
  lifecycle_rule {
    condition {
      age = var.retention_days
    }
    action {
      type = "Delete"
    }
  }

  # Move old backups to Nearline after 7 days (only if retention > 7)
  dynamic "lifecycle_rule" {
    for_each = var.retention_days > 7 ? [1] : []
    content {
      condition {
        age = 7
      }
      action {
        type          = "SetStorageClass"
        storage_class = "NEARLINE"
      }
    }
  }

  labels = var.labels
}

# =============================================================================
# Cloud Scheduler Job for Daily Backup
# =============================================================================

resource "google_cloud_scheduler_job" "firestore_backup" {
  count = var.enable_scheduled_backup ? 1 : 0

  project          = var.project_id
  name             = "fledgely-firestore-backup"
  description      = "Daily Firestore backup trigger"
  schedule         = var.backup_schedule
  time_zone        = var.backup_timezone
  attempt_deadline = "1800s" # 30 minutes

  http_target {
    http_method = "POST"
    uri         = var.backup_function_url

    oidc_token {
      service_account_email = var.scheduler_service_account
    }
  }

  retry_config {
    retry_count          = 3
    min_backoff_duration = "5s"
    max_backoff_duration = "60s"
  }
}

# =============================================================================
# Pub/Sub Topic for Backup Notifications (Optional)
# =============================================================================

resource "google_pubsub_topic" "backup_notifications" {
  count = var.enable_notifications ? 1 : 0

  project = var.project_id
  name    = "fledgely-backup-notifications"

  labels = var.labels
}

# =============================================================================
# IAM for Backup Operations
# =============================================================================

# Grant Firestore export permission to backup service account
resource "google_project_iam_member" "firestore_export" {
  project = var.project_id
  role    = "roles/datastore.importExportAdmin"
  member  = "serviceAccount:${var.backup_service_account}"
}

# Grant storage access to backup bucket
resource "google_storage_bucket_iam_member" "backup_writer" {
  bucket = google_storage_bucket.backups.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${var.backup_service_account}"
}

# Grant Cloud Functions invocation permission for scheduled backup
# Cloud Functions v2 uses Cloud Run under the hood, but we grant at project level
# since the function name is dynamically generated by Firebase
resource "google_project_iam_member" "functions_invoker" {
  count = var.enable_scheduled_backup ? 1 : 0

  project = var.project_id
  role    = "roles/cloudfunctions.invoker"
  member  = "serviceAccount:${var.scheduler_service_account}"
}
